name: Generate Solidity Documentation
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: 
          cd "backend" &&
          npm install

      - name: Generate Documentation via Hardhat docgen
        run: 
          cd "backend" &&
          npx hardhat docgen

      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
    
      - name: Deploy Documentation to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git reset --hard
          git add docs/
          git commit -m "Deploy documentation"
          git push --force https://x-access-token:${{ secrets.DOC_PAT }}@github.com/Slinf/copro-chain.git gh-pages