name: Lint Solidity Code
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd "backend" &&
          npm install

      - name: Install Solhint
        run: |
          cd "backend" &&
          npm install solhint@latest --save-dev

      - name: Check current directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Run Solhint
        run: |
          npx solhint 'backend/contracts/**/*.sol'
