name: Security Analysis with Slither

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd "backend" && 
          npm install
          npm install @openzeppelin/contracts

      - name: Install Python and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Set up Solidity Compiler (solc)
        run: |
          pip3 install solc-select
          solc-select install 0.8.22
          solc-select use 0.8.22

      - name: Install Slither
        run: |
          cd "backend" &&
          pip3 install slither-analyzer

      - name: Run Slither Security Analysis
        run: |
          cd "backend" &&
          slither contracts/
