name: Security Analysis with Slither

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Python and pip
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Install dependencies
        run: |
         cd "backend" && 
         pip3 install

      - name: Install Slither
        run: |
          cd "backend" &&
          pip install slither-analyzer

      - name: Run Slither Security Analysis
        run: |
          cd "backend" &&
          slither contracts/
